### ISSUE TITLE
hw1

### ISSUE THREAD

**Issue by ivan1kolesov** [BestPracticeSchool/BPS-BaseProgramming_1_2019#1]
https://github.com/enotik1poloskyn/hw_1.git

колесов иван владимирович

**Comment by vlasove** [comment]
task1 --- 10/10

**Comment by vlasove** [comment]
task2 --- неверный формат вывода. Обрати внимание, как описан пример вывода и на регистр букв в выводе. Это важно.
Случая с отрицательными числами тут нет - ``` else ``` не нужен.

**Comment by vlasove** [comment]
task3 --- 15/15

**Comment by vlasove** [comment]
task4 --- 17/17

**Comment by vlasove** [comment]
task5 --- неверный формат вывода. Обрати внимание, что должно выводиться, в случае если корни отсутствуют по той или иной причине.
Также обрати внимание на регистр во вспомогательных к ответу строках.

**Comment by ivan1kolesov** [comment]
поменял

**Comment by vlasove** [comment]
task2 --- 12/12

**Comment by vlasove** [comment]
task5 --- неверный вывод. Проверь случай ввода 0 2 0.
И вместо None лучше возвращай ```" "```. Так как ты будешь всегда печатать ```print(None)```, как например в случае выше.

**Comment by ivan1kolesov** [comment]
все ?

**Comment by vlasove** [comment]
task5 --- 10/10

**Comment by vlasove** [comment]
Красавчик!

**BestPractice гордится тобой!**

**Comment by ivan1kolesov** [comment]
ты тоже ничего
