### ISSUE TITLE
HW Иванов И.А

### ISSUE THREAD

**Issue by tbR12** [BestPracticeSchool/BPS-BaseProgramming_1_2019#3]
https://github.com/tbR12/hw

**Comment by vlasove** [comment]
task1 --- неверный формат. Посмотри пожалуйста,как называется у тебя файл с номером домашки  и какая задача в нем лежит.

Также обрати внимание, что в той задаче формат вывода расходится с твоим. 
Во-первых, нужно использовать латинские символы, а во-вторых - каждый ответ должен отображаться на новой строчке

**Comment by vlasove** [comment]
task2 --- неверный формат вывода. **См.выше** , отписал тебе про эту задачу

**Comment by vlasove** [comment]
task3 --- неверный ответ. Твое решение пока не проходит тесты. 
Попробуй следующий подход: треугольник прямоугольный --- если между сторонами этого треугольника выполняется соотношение 
```
сторона1^2 + сторона2^2 == сторона3^2
```
Введеные в задаче 3 числа - это и есть требуемые стороны. Рекомендую рассмотреть все возможные комбинации этих сторон. Может в какой-то из них условие выше будет выполнено:)

**Comment by vlasove** [comment]
task 4: 
В 4 задаче необходимо подсчитать НОД между двумя числами (эта задачка для самостоятельного поиска инфы в гугле, да да)
Там ты сможешь найти нужный алгоритм подсчета НОДа, твоя же задача - правильно вкрутить его в решение и сделать так, чтобы формат вывода удовлетворял условию задачи.

Подсказка: ```  НОД на питоне ``` в гугле  по первой ссылке дает приемлимый алгоритм вычисления :)

**Comment by vlasove** [comment]
task5:
В данной задаче необходимо решить квадратное уравнение ( на вход программе подаются коэффициенты в квадратном уравнении). Подробнее о том, как руками (с точки зрения математики) решаются квадратные уравнения : https://www.berdov.com/docs/equation/quadratic_equations/

Тебе лишь нужно реализовать это в коде.

Обрати внимание, что квадратное уравнение имеет вид:
``` Ax^2 + Bx + C = 0```
Так вот как раз на вход программе приходят:
```
A = int(input())
B = int(input())
C = int(input())
...
....
```

**Comment by vlasove** [comment]
task1 --- неверный формат вывода. Не хватает кое-какого знака препинания, который есть в условии задачи

**Comment by vlasove** [comment]
task2 --- зачтено

**Comment by vlasove** [comment]
task3 --- неверный формат вывода. Обрати внимание на **размер** букв в выводе в условии задачи

**Comment by vlasove** [comment]
task4 --- неверный формат вывода. Лишний пробел. Нужно, чтобы было ```NOD:10```, у тебя сейчас вывод ```NOD: 10```

**Comment by vlasove** [comment]
task5 --- неверное решение. Рассмотри случай **0 0 1**

**Comment by vlasove** [comment]
task3 --- неверное решение. Что выведет твоя программа если ей на вход дать стороны **5 4 2**? Такой треугольник - непрямоугольный

**Comment by vlasove** [comment]
task5 --- неверное решение. Рассмотри случай **0 1 0**. Это соответствует уравнению
```bx = 0 ```, где есть решение ```x = 0```

**Comment by vlasove** [comment]
task1 --- зачтено

**Comment by vlasove** [comment]
task3 --- неверное решение. Что будет, если я введу **5 4 3**? Вроде геометрия говорит, что это прямоугольный треугольник

**Comment by vlasove** [comment]
task4 --- зачтено

**Comment by vlasove** [comment]
task5 --- зачтено

**Comment by vlasove** [comment]
task3 --- зачет

**Comment by vlasove** [comment]
Красавчик!!

**BestPractice гордится тобой!**
