### ISSUE TITLE
Шадрин Антон Павлович

### ISSUE THREAD

**Issue by Barmark-learn** [BestPracticeSchool/BPS-BaseProgramming_1_2019#4]
https://github.com/Barmark-learn?tab=repositories

**Comment by vlasove** [comment]
task1 --- неверный формат вывода. Обрати внимание, как выглядит выходная строка в примере задачи.

**Comment by vlasove** [comment]
task2 --- неверный формат вывода. Обрати внимание, какими символами отпечатывается ответ и на скольких строчках он доступен

**Comment by vlasove** [comment]
task3 --- неверный ответ. Рассмотри случай **5 4 3**

**Comment by vlasove** [comment]
task3 --- 15/15

**Comment by vlasove** [comment]
task4 --- неверный формат вывода. Лишний пробел в строке вывода

**Comment by vlasove** [comment]
task1 --- 10/10

**Comment by vlasove** [comment]
task2 --- 12/12

**Comment by vlasove** [comment]
task4 --- 17/17

**Comment by vlasove** [comment]
task5 --- неверное решение. Рассмотри случай **0 0 1**

**Comment by Barmark-learn** [comment]
> task5 --- неверное решение. Рассмотри случай 0 0 1

Исправил

**Comment by vlasove** [comment]
task5 --- неверный формат вывода. В случае, когда корней нет - всегда печатается пустая строка,а не фраза ```Нет корней```

**Comment by Barmark-learn** [comment]
> task5 --- неверный формат вывода. В случае, когда корней нет - всегда печатается пустая строка,а не фраза Нет корней
Готово

**Comment by Barmark-learn** [comment]
> task5 --- неверный формат вывода. В случае, когда корней нет - всегда печатается пустая строка,а не фраза Нет корней

готово

**Comment by vlasove** [comment]
task5 --- неверный ответ. В случаях, когда корни отсутствуют при **D < 0 ** - твои ```print(" ")``` не отрабатывают как нужно. Рекомендую вставить в них какой-нибудь символ и посмотреть, что не так

**Comment by Barmark-learn** [comment]
> task5 --- неверный ответ. В случаях, когда корни отсутствуют при **D < 0 ** - твои print(" ") не отрабатывают как нужно. Рекомендую вставить в них какой-нибудь символ и посмотреть, что не так

Исправил.

**Comment by vlasove** [comment]
task5 --- зачтено

**Comment by vlasove** [comment]
Красавчик!!

**BestPractice гордится тобой!**
